apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: worker-app
    image: dockersamples/examplevotingapp_worker
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

# System.AggregateException: One or more errors occurred. (No such device or address) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
#    at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
#    at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
#    --- End of inner exception stack trace ---
#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
#    at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
#    at Npgsql.NpgsqlConnector.RawOpen(NpgsqlTimeout timeout)
#    at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout)
#    at Npgsql.ConnectorPool.Allocate(NpgsqlConnection conn, NpgsqlTimeout timeout)
#    at Npgsql.NpgsqlConnection.OpenInternal()
#    at Worker.Program.OpenDbConnection(String connectionString) in /code/src/Worker/Program.cs:line 74
#    at Worker.Program.Main(String[] args) in /code/src/Worker/Program.cs:line 19
# ---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: No such device or address
#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
#    at System.Net.Dns.EndGetHostAddresses(IAsyncResult asyncResult)
#    at System.Net.Dns.<>c.<GetHostAddressesAsync>b__14_1(IAsyncResult asyncResult)
#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---